version: 2

project_name: cldo

builds:
  - id: cldo
    main: ./cmd/cldo
    binary: cldo

    env:
      - CGO_ENABLED=1

    goos:
      - darwin
      - linux

    goarch:
      - amd64
      - arm64
